# These are supported funding model platforms

# github: [fvcproductions, fvntr] neither of us are in the beta yet
patreon: techqueria
open_collective: techqueria
ko_fi: techqueria
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://techqueria.org/support-us/
